DESIGN=clocks
DESDIR=C:\Users\myles.clark\OneDrive - University of Florida\Desktop\ClockTesting\designer\clocks
TARGET_DIR=C:\Users\myles.clark\OneDrive - University of Florida\Desktop\ClockTesting\designer\clocks
FAM=SmartFusion2
DIE=PA4M1000_N
PACKAGE=vf400
PINRPT_BY_NAME=1
PINRPT_BY_NUMBER=1
BANK_REPORT=1
IOREG_REPORT=1
